// Regenerates docs/IMAGES.md from the catalogue, so the photo list never drifts
// from the code. Run: npm run images:doc (Node 22.18+ strips TS types natively)
import { writeFileSync, existsSync } from "node:fs";
import { products, photoSrc, COLORS } from "../src/lib/products.ts";
import { HOME_IMAGES } from "../src/lib/editorial.ts";

const has = (src) => existsSync(new URL(`../public${src}`, import.meta.url));
const mark = (src) => (has(src) ? "✅" : "⬜");

let total = 0;
let done = 0;
const count = (src) => {
  total++;
  if (has(src)) done++;
};

let body = "";
body += "## Home page\n\nFolder: `public/images/home/`\n\n";
body += "| | File | Alt text | What the photo should show |\n|---|---|---|---|\n";
for (const img of Object.values(HOME_IMAGES)) {
  count(img.src);
  body += `| ${mark(img.src)} | \`${img.src.split("/").pop()}\` | ${img.alt} | ${img.brief} |\n`;
}

body += "\n## Products\n\nFolder: `public/images/products/`. Portrait **4:5**, at least **1600×2000 px**. ";
body += "Shot 1 is the one used on cards, in the cart and in search, so it should show the whole piece in its first colour.\n";
for (const p of products) {
  body += `\n### ${p.name} · ${p.drop}\n\nFirst colour: ${COLORS[p.colors[0]].name}. Colours: ${p.colors.map((c) => COLORS[c].name).join(", ")}\n\n`;
  body += "| | File | Alt text / brief |\n|---|---|---|\n";
  for (let i = 1; i <= p.photos; i++) {
    const src = photoSrc(p.slug, i);
    count(src);
    body += `| ${mark(src)} | \`${src.split("/").pop()}\` | ${p.shots[i - 1] ?? p.name} |\n`;
  }
}

const head = `# Concrete — photo list

Every photo on the site is a placeholder until a file with the exact name below is dropped into \`public/\`.
The placeholder shows the expected file name and the alt text, so it's clear on the page which file goes where.
No code changes are needed: add the file, reload, done.

**Status: ${done} of ${total} photos in place.** This file is generated by \`npm run images:doc\` — edit shot descriptions in \`src/lib/products.ts\` and \`src/lib/editorial.ts\`, not here.

## Rules for every photo

- **Format:** \`.webp\`, quality 80–85. Next.js resizes and serves the right size automatically.
- **Look:** cold, overcast daylight, desaturated, concrete textures. No warm filters, no neon.
- **No third-party brands.** No visible logos (HUF, Fnatic, Adidas etc.) on clothes, shoes or background — they were in the Figma draft and are removed here.
- **People:** models with consented releases or licensed stock only.
- **Alt text** already lives in code; if a shot changes, update its line in \`products.ts\` / \`editorial.ts\` so the alt matches the new photo.

`;
writeFileSync(new URL("../docs/IMAGES.md", import.meta.url), head + body);
console.log(`docs/IMAGES.md written — ${done}/${total} photos in place`);
