// Regenerates docs/IMAGES.md from the catalogue, so the photo list never drifts
// from the code. Run: npm run images:doc (Node 22.18+ strips TS types natively)
import { writeFileSync, existsSync } from "node:fs";
import { products, photoSrc, photoAlt, COLORS } from "../src/lib/products.ts";
import { HOME_IMAGES } from "../src/lib/editorial.ts";

const has = (src) => existsSync(new URL(`../public${src}`, import.meta.url));
const mark = (src) => (has(src) ? "✅" : "⬜");

let total = 0;
let done = 0;
const count = (src) => {
  total++;
  if (has(src)) done++;
};

let body = "";
body += "## Home page\n\nFolder: `public/images/home/`\n\n";
body += "| | File | Alt text | What the photo should show |\n|---|---|---|---|\n";
for (const img of Object.values(HOME_IMAGES)) {
  count(img.src);
  body += `| ${mark(img.src)} | \`${img.src.split("/").pop()}\` | ${img.alt} | ${img.brief} |\n`;
}

body += "\n## Products\n\nFolder: `public/images/products/`. Portrait **4:5**, generated source resolution, kept without artificial upscaling. ";
body += "Cards and search use shot 1 in the first colour. PDP galleries and cart thumbnails use the selected colour.\n";
for (const p of products) {
  body += `\n### ${p.name} · ${p.drop}\n\nFirst colour: ${COLORS[p.colors[0]].name}. Colours: ${p.colors.map((c) => COLORS[c].name).join(", ")}\n\n`;
  body += "| | File | Alt text / brief |\n|---|---|---|\n";
  for (const color of p.colors) {
    body += `| | **${COLORS[color].name}** | |\n`;
    for (let i = 1; i <= p.photos; i++) {
      const src = photoSrc(p.slug, i, color);
      count(src);
      body += `| ${mark(src)} | \`${src.split("/").pop()}\` | ${photoAlt(p, i, color)} |\n`;
    }
  }
}

const head = `# Concrete — photo list

The catalogue below maps every editorial image and every product colourway to its actual file.
Missing files use the site's existing photo placeholder. Colour galleries are resolved by \`photoSrc\` in \`src/lib/products.ts\`.

**Status: ${done} of ${total} photos in place.** This file is generated by \`npm run images:doc\` — edit shot descriptions in \`src/lib/products.ts\` and \`src/lib/editorial.ts\`, not here.

## Rules for every photo

- **Format:** \`.webp\`, quality 80–85. Next.js resizes and serves the right size automatically.
- **Look:** cold, overcast daylight, desaturated, concrete textures. No warm filters, no neon.
- **No third-party brands.** No visible logos (HUF, Fnatic, Adidas etc.) on clothes, shoes or background — they were in the Figma draft and are removed here.
- **People:** this portfolio uses AI-generated fictional adult models; no real model releases or physical product photography are claimed.
- **Alt text** already lives in code; if a shot changes, update its line in \`products.ts\` / \`editorial.ts\` so the alt matches the new photo.

`;
writeFileSync(new URL("../docs/IMAGES.md", import.meta.url), head + body);
console.log(`docs/IMAGES.md written — ${done}/${total} photos in place`);
